### PR TITLE
Merge TorchScript tests with regular tests

### PR DESCRIPTION
**Pull request by agoscinski**
Hopefully this reduces the testing time significantly

### CODE REVIEW

**Comment by agoscinski** [comment]
PR requires fix for https://github.com/lab-cosmo/metatensor/issues/374

**Comment by agoscinski** [comment]
okay https://github.com/lab-cosmo/metatensor/issues/374 has been fixed. I wait till https://github.com/lab-cosmo/torch_spex/pull/31 has been merged and then change metatensor version here and rebase

**Comment by agoscinski** [comment]
Looking at the CI failure, there seems to be still some kind of memory error
```
E           ValueError: could not find blocks matching the selection (a_i=0, lam=-1883631648, sigma=21991)
```
Will look into this some other time.

**Comment by Luthaf** [comment]
Looks fine with the released version of metatensor \o/

**Pull request merged**
